---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dname
  labels:
    app: dname
data:
  db.internal.zone: |
    $TTL    3600
    @       IN      SOA     kwaci.db.internal. root.db.internal. (
                            2021122300           ; Serial
                                  3600           ; Refresh [1h]
                                    600          ; Retry   [10m]
                                  86400          ; Expire  [1d]
                                    600 )        ; Negative Cache TTL [1h]
    ;
    @                       IN      NS      kwaci.db.internal.
    kwaci                   IN      A       172.20.1.90
    persistence-id-stag	    IN		  DNAME	  persistence-id-stag.svc.cluster.local.
    persistence-th-stag	    IN		  DNAME	  persistence-th-stag.svc.cluster.local.
    persistence-vn-stag	    IN		  DNAME	  persistence-vn-stag.svc.cluster.local.
   
  named.conf: |
    acl allow-clients {
      localhost;
      10.0.0.0/8;
      172.16.0.0/12;
    };

    options {
      directory "/var/cache/bind";

      recursion yes;
      allow-query { allow-clients; };

      forwarders {
        169.254.169.254;
      };
      forward only;

      dnssec-enable yes;
      dnssec-validation yes;

      # conform to RFC1035
      auth-nxdomain no;
    };

    // prime the server with knowledge of the root servers
    zone "." {
      type hint;
      file "/usr/share/dns/root.hints";
    };

    // be authoritative for the localhost forward and reverse zones, and for
    // broadcast zones as per RFC 1912

    zone "localhost" {
      type master;
      file "/etc/bind/db.local";
    };

    zone "127.in-addr.arpa" {
      type master;
      file "/etc/bind/db.127";
    };

    zone "0.in-addr.arpa" {
      type master;
      file "/etc/bind/db.0";
    };

    zone "255.in-addr.arpa" {
      type master;
      file "/etc/bind/db.255";
    };

    zone "cluster.local" {
      type forward;
      forward only;
      forwarders {
        10.3.240.10;
        10.3.251.204;
      };
    };

    zone "db.internal" {
      type master;
      file "/etc/bind/db.internal.zone";
    };

