apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dname
  name: dname
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dname
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dname
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: infra.ruangguru.com/type
                operator: NotIn
                values:
                - persistence
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - dname
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: asia.gcr.io/silicon-airlock-153323/infrastructure/dname:f5e6ad8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          exec:
            command:
            - "dig"
            - "+short"
            - "kube-dns.kube-system.svc.cluster.local"
            - "@127.0.0.1"
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: dname
        ports:
        - containerPort: 53
          name: dns-local
          protocol: UDP
        readinessProbe:
          failureThreshold: 3
          exec:
            command:
            - "dig"
            - "+short"
            - "kube-dns.kube-system.svc.cluster.local"
            - "@127.0.0.1"
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 200m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/config/dname
          name: dname
      volumes:
      - name: dname
        configMap:
          name: dname
      dnsPolicy: Default
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
